version: 0.0
os: linux
files:
  - source: /
    destination: /home/deploy/codedeploy/fe/
    permissions:
      - object: "*"
        owner: deploy
        group: deploy
hooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 300
      runas: deploy
