import './globals.css';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import React from 'react';
import ThemeSwitchProvider from '../providers/themeProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const FontJakarta = Plus_Jakarta_Sans({
  variable: '--font-jakarta',
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '700', '800'],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${FontJakarta.variable} ${FontJakarta.className} bg-primary-bg`}>

        <ThemeSwitchProvider>
          {children}
        </ThemeSwitchProvider>
      </body>
    </html>
  );
}
