import FacebookIcon from '@/icons/facebook.icon';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';
import TwitterIcon from '@/icons/twitter.icon';
import LinkedInIcon from '@/icons/linkedin.icon';
import YoutubeIcon from '@/icons/youtube.icon';
import HamburgerIcon from '@/icons/hamburger.icon';
import DarkModeIcon from '@/icons/darkmode.icon';
import LightModeIcon from '@/icons/lightmode.icon';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <div
              className="
                flex
                justify-between
                px-6
                py-3
                relative
                lg:px-20
                lg:pt-3
                lg:pb-4
              "
            >
              <div>
                <Image width={173} height={53} alt="Root On logo" src={'/r-oot-on-logo-svg.svg'} />
              </div>
              <div
                className="
                  gap-[62px]
                  justify-end
                  items-center
                  text-white
                  text-base
                  font-bold
                  hidden
                  lg:flex
                "
              >
                <span>
                  <Link href={'/'}> About Us </Link>
                </span>
                <span>
                  <Link href={'/'}> Services </Link>
                </span>
                <span>
                  <Link href={'/'}> Coaching </Link>
                </span>
                <span>
                  <Link href={'/'}> Blogs </Link>
                </span>
                <span>
                  <Link href={'/'}> Contact Us </Link>
                </span>
                <span>
                  <Link href={'/'}> Tools </Link>
                </span>
              </div>
              <div
                className="
                  flex
                  items-center
                  hover:cursor-pointer
                  gap-4
                "
              >
                <div className=' flex gap-0 w-12 lg:w-16 lg:h-8 h-6'>
                  <span className=' w-1/2 h-full bg-white flex justify-center items-center'>
                    <DarkModeIcon />
                  </span>
                  <span className=' w-1/2 h-full bg-white opacity-[0.23] flex justify-center items-center'>
                    <LightModeIcon />
                  </span>
                </div>
                <span className=' lg:hidden'>
                  <HamburgerIcon />
                </span>
              </div>
            </div>
            <div
              className="
                  border-b
                  border-[#d8d8d8]
                  h-0
                  mx-6
                  opacity-50
                "
            />
          </nav>
        </header>
        {children}
        <footer className=" pb-[76px]">
          <div className="
              border-t
              border-b
              border-[#d2d2d2]
              py-5
              px-6
              flex
              flex-col
              lg:flex-row
              lg:justify-around
              justify-cente
            "
          >
            <div className=' lg:flex lg:flex-col justify-between'>
              <Image width={180} height={54} alt="logo" src={'/r-oot-on-logo-black.svg'} className=" mb-6 mx-auto" />
              <div className=" flex flex-col gap-8 mb-7">
                <p className=" m-auto text-sm">Follow us on</p>
                <div className=" flex gap-12 justify-center">
                  <span>
                    <FacebookIcon />
                  </span>
                  <span>
                    <TwitterIcon />
                  </span>
                  <span>
                    <LinkedInIcon />
                  </span>
                  <span>
                    <YoutubeIcon />
                  </span>
                </div>
              </div>
            </div>
            <div
              className="
                flex
                gap-10
                flex-wrap
                justify-between
                text-sm
                font-semibold
              "
            >
              <div className=' flex flex-col gap-3'>
                <p>Careers</p>
                <p>Privacy Policy</p>
                <p>Terms & Condition</p>
                <p>FAQs</p>
                <p>QnA Forum</p>
              </div>
              <div className=' flex flex-col gap-3'>
                <p>Book a Meeting RCIC</p>
                <p>Disclaimer</p>
                <p>GCKey vs APR </p>
                <p>Affiliate Program</p>
                <p>Sitemap</p>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
