export const initialStates = {
  // personal
  age: '',
  country_of_citizenship: '',
  country_of_residence: '',
  marital: '',
  do_you_have_any_children_under_the_age_of_22_: '',
  how_many_children_do_you_have_aged_13_to_21_: '',
  how_many_children_do_you_have_under_the_age_of_13_: '',
  preferred_destination_in_canada: '',
  where_in_manitoba_do_you_wish_to_reside: '',
  have_you_ever_been_to_quebec_before_: '',
  // Language
  english_writing: '',
  english_reading: '',
  english_listening: '',
  english_speaking: '',
  french_listening: '',
  french_speaking: '',
  french_reading: '',
  french_writing: '',
  // educational
  have_you_completed_high_school__12th_grade__: '',
  have_you_received_any_education_or_training_other_than_high_school_: '',
  // work HIstory
  have_you_done_any_paid_work_during_the_last_10_years_: '',
  // express entry
  have_you_already_submitted_an_express_entry_profile_to_the_government_of_canada_within_the_past_12_: '',
  have_you_already_received_an_invitation_to_apply_for_permanent_residence_from_the_government_of_can: '',
  // canadian job offer
  do_you_have_a_written_job_offer_from_a_canadian_employer_: '',
  occupation_as_per_offer: '',
  province_or_territory_of_the_canadian_job_offer: '',
  what_is_the_contract_duration_for_the_canadian_job_offer_: '',
  work_hours_for_the_canadian_job_offer: '',
  is_this_canadian_job_offer_supported_by_a_labour_market_impact_assessment__lmia__: '',
  do_you_have_related_education__training__previous_work_experience_and_any_alberta_licensing_needed_: '',
  in_what_region_is_the_job_that_is_being_offered_in_british_columbia_: '',
  are_you_currently_working_in_the_northeast_development_region_of_british_columbia_: '',
  what_is_the_annual_wage_of_the_canadian_job_offer_: '',
  how_many_years_of_full_time__or_part_time_equivalent__work_experience_do_you_have_that_is_directly_: '',
  completed__itabc_s__challenge_certification_process_: '',
  have_you_received_an_invitation_to_apply_from_the_manitoba_provincial_nominee_program_for_canadian_: '',
  is_employer_offering_job_part_of_atlantic_immigration_pilot_by_the_atlantic_province_: '',
  is_this_job_offer_related_to_your_field_of_study_saskatchewan__: '',
  is_the_canadian_job_offer_exempt_from_lmia: '',
  // family or friends
  close_friend_living_in_manitoba_18_years_or_older_: '',
  family_members_or_relatives_living_in_canada_18_years_or_older_: '',
  relationship_to_family_member_in_canada: '',
  residency_status_of_family_member: '',
  family_member_living_in: '',
  family_member_living_in_current_area_for_: '',
  // networth
  preferred_currency_for_networth: '',
  total_networth_amount: '',
  // contact info
  firstname: '',
  lastname: '',
  email: '',
  mobilephone: '',
  consultation_type: '',
  i_consent_to_receive_email_communications_from_root_on_regarding_my_canadian_immigration_inquiry_:'',
};
